This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test03.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test03.bc
  -1
  1
  0
  -1
  1
  0
  -1
  1
  0
  0
  -1
  1
  -1
  1
  0
  0
  1
  -1
