This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test21.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test21.bc
  1
  1
  1
  1
  1
  2
  3
  100
  Cons (3, Cons (2, Cons (1, Cons (6, Cons (5, Cons (4, Cons (3, Cons (2, Cons (1, Nil)))))))))
