This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test25.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test25.bc
  Cloning int: 5
  Cloning string: abc
  Cloning array: [1, 2, 3, 4, 5]
  Cloning sexp: A (1, 2, 3, 4, 5)
  Cloning closure: address ok, 5, 6
