This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test23.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test23.bc
  1
  {2, 3, 4}
  2
