This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test32.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test32.bc
  Flattening: 0
  Flattening: {A, B, C, D}
