This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test24.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test24.bc
  3
  {1}
  {1}
