This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test33.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test33.bc
  {}.string: 0
  {}.stringcat: 
