This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test26.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test26.bc
  Number of commands-line arguments: 1
    arg [0 ] = "test26.bc"
