This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test22.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test22.bc
  0
  {1, 2, 3, 4}
  {{1}, {2, 3}, {4, {5, 6}}}
  {1, 2, 3, 4}
