This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test09.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test09.bc
  Parsing a*| against "aa"... Succ ({"a", "a"})
  Parsing a+| against "aa"... Succ ({"a", "a"})
  Parsing list(a)| against "a"... Succ ({"a"})
  Parsing list(a)| against "a,a"... Succ ({"a", "a"})
  Parsing list0(a)| against ""... Succ (0)
