This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test11.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test11.bc
  Succ ("a")
  Succ (Add ("a", "a"))
  Succ (Sub ("a", "a"))
  Succ (Sub (Add ("a", "a"), "a"))
  Succ (Add ("a", Mul ("a", "a")))
  Succ (Sub (Mul ("a", "a"), Div ("a", "a")))
