This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test14.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test14.bc
  Succ (Add ("a", Sub ("a", "a")))
  Succ (Mul (Div (Mul ("a", "a"), "a"), "a"))
  Succ (Add (Mul ("a", "a"), Sub (Div ("a", "a"), Mul ("a", "a"))))
