This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test29.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test29.bc
  Succ (Seq ("a", "b"))
  Succ (Alt ("a"))
  Succ (Alt ("b"))
  Succ (Rep ({"a", "a", "a"}))
