This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test08.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test08.bc
  6
  120
  5040
