This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test34.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test34.bc
   ' " ` % \  
  	 \h @ $ # ; [ ] 
