This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test05.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test05.bc
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
