This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test10.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test10.bc
  Parsing "aaa" with many ... Succ ({"a", "a", "a"})
  Parsing "ab" with bad_alter ... Succ ("ab")
