This file was autogenerated.
  $ ../../../src/Driver.exe -runtime ../../../runtime -I ../../../runtime -I ../../../stdlib/x64 -b ../test02.lama
  $ ../../../virtual_machine/lama.exe -I ../../../stdlib/x64 test02.bc
  Assn ("x", Dec ("3"))
