This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test09.lama -o test
  $ ./test
  Parsing a*| against "aa"... Succ ({"a", "a"})
  Parsing a+| against "aa"... Succ ({"a", "a"})
  Parsing list(a)| against "a"... Succ ({"a"})
  Parsing list(a)| against "a,a"... Succ ({"a", "a"})
  Parsing list0(a)| against ""... Succ (0)
