This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test14.lama -o test
  $ ./test
  Succ (Add ("a", Sub ("a", "a")))
  Succ (Mul (Div (Mul ("a", "a"), "a"), "a"))
  Succ (Add (Mul ("a", "a"), Sub (Div ("a", "a"), Mul ("a", "a"))))
