This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test03.lama -o test | grep -v 'section .note.GNU-stack'
  /usr/bin/ld: warning: /tmp/build_7bb8d6_dune/ccQnDDog.o: missing .note.GNU-stack section implies executable stack
  /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
  [1]
  $ ./test
  -1
  1
  0
  -1
  1
  0
  -1
  1
  0
  0
  -1
  1
  -1
  1
  0
  0
  1
  -1
