This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test22.lama -o test
  $ ./test
  0
  {1, 2, 3, 4}
  {{1}, {2, 3}, {4, {5, 6}}}
  {1, 2, 3, 4}
