This file was autogenerated.
  $ LAMA=../../runtime ../../src/Driver.exe -I ../x64 -ds -dp test05.lama -o test
  /usr/bin/ld: warning: printf.o: missing .note.GNU-stack section implies executable stack
  /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
  $ ./test
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
