This file was autogenerated.
  $ LAMA=../../runtime ../../src/Driver.exe -I ../x64 -ds -dp test03.lama -o test
  /usr/bin/ld: warning: /tmp/build_f976a4_dune/ccZxTdzd.o: missing .note.GNU-stack section implies executable stack
  /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
  $ ./test
  -1
  1
  0
  -1
  1
  0
  -1
  1
  0
  0
  -1
  1
  -1
  1
  0
  0
  1
  -1
