This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test15.lama -o test
  $ ./test
  Succ (Eq ("a", "a"))
  Succ (Eq (Mul ("a", "a"), Mul ("a", "a")))
  Succ (Eq (Add (Mul ("a", "a"), Sub (Div ("a", "a"), Mul ("a", "a"))), Sub (Mul ("a", "a"), "a")))
  Fail ({""*" expected at"}, 1, 2)
