This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test05.lama -o test
  $ ./test
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
  Cached: 1
