This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test28.lama -o test
  $ ./test
  Succ (Seq ("a", "b"))
  Succ (Alt ("a"))
  Succ (Alt ("b"))
  Succ (Rep ({"a", "a", "a"}))
