This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test26.lama -o test
  $ ./test
  Number of commands-line arguments: 1
    arg [0 ] = "./test"
