This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test03.lama -o test
  $ ./test
  -1
  1
  0
  -1
  1
  0
  -1
  1
  0
  0
  -1
  1
  -1
  1
  0
  0
  1
  -1
