This file was autogenerated.
  $ LAMA=../../runtime ../../src/Driver.exe -I ../x64 -ds -dp test17.lama -o test
  /usr/bin/ld: warning: printf.o: missing .note.GNU-stack section implies executable stack
  /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
  $ ./test
  Lazy body: 0
  Lazy body: 1
  Lazy body: 2
  Lazy body: 3
  Lazy body: 4
  Lazy body: 5
  Lazy body: 6
  Lazy body: 7
  Lazy body: 8
  Lazy body: 9
  First force: 100
  Second force: 100
