This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test17.lama -o test | grep -v 'section .note.GNU-stack'
  /usr/bin/ld: warning: printf.o: missing .note.GNU-stack section implies executable stack
  /usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
  [1]
  $ ./test
  Lazy body: 0
  Lazy body: 1
  Lazy body: 2
  Lazy body: 3
  Lazy body: 4
  Lazy body: 5
  Lazy body: 6
  Lazy body: 7
  Lazy body: 8
  Lazy body: 9
  First force: 100
  Second force: 100
