This file was autogenerated.
  $ ../../src/Driver.exe -runtime ../../runtime -I ../../runtime -I ../../stdlib/x64 -ds -dp test10.lama -o test
  $ ./test
  Parsing "aaa" with many ... Succ ({"a", "a", "a"})
  Parsing "ab" with bad_alter ... Succ ("ab")
