name: Build in docker
on:
  push:
    branches:
      - '1.30'
      - 'i686-cross'

env:
  OPAMROOT: /home/opam/.opam
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: kakadu18/ocaml:lama
      options: --user user

    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4

      - run: |
          opam install . --depext-only --with-test --with-doc
          opam install . --deps-only --with-test --with-doc


      - name: List installed packages
        run: opam list

      - run: opam exec -- dune build --profile=release
      - run: opam exec -- dune test regression/ stdlib/regression
